name: test-python
base: core20
version: '0.1'
summary: test python plugin with gnome-3-38 and overriding the path and pythonpath
description: |
  This fails to install pip

grade: devel
confinement: devmode

parts:
  my-part:
    plugin: python
    source: .
    build-environment:
      - PATH: /usr/bin:$PATH
      - PYTHONPATH: ''
    requirements: [requirements.txt]

apps:
  test-python:
    command: bin/test-python
    extensions: [gnome-3-38]