name: test-python
base: core18
version: '0.1'
summary: test python plugin w/ gnome-3-38, override path&pythonpath, and installing pip
description: |
  This fails to install the python project's files

grade: devel
confinement: devmode

parts:
  my-part:
    plugin: python
    source: .
    build-environment:
      - PATH: /usr/bin:$PATH
      - PYTHONPATH: ''
    build-packages:
      - python3-pip
    requirements: [requirements.txt]

apps:
  test-python:
    command: bin/test-python
    extensions: [gnome-3-34]