name: test-python
base: core20
version: '0.1'
summary: test python plugin with gnome-3-38 extension
description: |
  This fails to build at all

grade: devel
confinement: devmode

parts:
  my-part:
    plugin: python
    source: .
    requirements: [requirements.txt]

apps:
  test-python:
    command: bin/test-python
    extensions: [gnome-3-38]